#ifndef MELAMPIG_ORM_H
#define MELAMPIG_ORM_H

#include "defines.h"
#include "exports.h"
#include "errors.h"

#include "util.h"
#include "attr.h"

#include "keeper.h"

#include "object.h"
#include "tree.h"
#include "link.h"

#include "action.h"
#include "memberaddress.h"
#include "coachaddress.h"
#include "wrestleraddress.h"
#include "refereeaddress.h"
#include "addresstype.h"
#include "age.h"
#include "circle.h"
#include "classify.h"
#include "coach.h"
#include "competition.h"
#include "competitionmember.h"
#include "competitionreferee.h"
#include "competitionstyle.h"
#include "competitionteam.h"
#include "competitionweight.h"
#include "competitionwrestler.h"
#include "cround.h"
#include "ctour.h"
#include "comptype.h"
#include "fight.h"
#include "fight_log.h"
#include "fround.h"
#include "gender.h"
#include "geo.h"
#include "mat.h"
#include "match.h"
#include "member.h"
#include "position.h"
#include "rang.h"
#include "referee.h"
#include "role.h"
#include "style.h"
#include "team.h"
#include "weight.h"
#include "wrestler.h"
#include "cgroup.h"

#include "project.h"

#endif // MELAMPIG_ORM_H
